version: '3.8'

services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}-backend:latest
    container_name: order_system_backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://orderuser:${POSTGRES_PASSWORD}@database:5432/order_system
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=production
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - order_system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}-frontend:latest
    container_name: order_system_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - order_system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: order_system_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
      - frontend
    networks:
      - order_system_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: postgres:13-alpine
    container_name: order_database
    restart: unless-stopped
    environment:
      - POSTGRES_DB=order_system
      - POSTGRES_USER=orderuser
      - POSTGRES_PASSWORD=orderpass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - order_system_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orderuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: order_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - order_system_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  order_system_network:
    driver: bridge